### ISSUE TITLE
The ./DatabaseTransfer.sh failed to build

### ISSUE THREAD

**Issue by ioualha** [digexp/DX.Kubernetes.IBM-Cloud#12]
Hi,

The ./DatabaseTransfer.sh failed to build

```
[java] [2018-03-07 16:51:30.638] Transferring table --{ JCR.WCM_SYND_SESSION}-- to table --{JCR.WCM_SYND_SESSION }--
     [java] [2018-03-07 16:51:30.873] Transferring table --{ JCR.ICMSTVIEWACCESS}-- to table --{JCR.ICMSTVIEWACCESS }--
     [java] [2018-03-07 16:51:31.271] Transferring table --{ JCR.WCM_OBJECTS}-- to table --{JCR.WCM_OBJECTS }--
     [java] [2018-03-07 16:51:31.459] Transferring table --{ JCR.WCM_TIMERS}-- to table --{JCR.WCM_TIMERS }--
     [java] [2018-03-07 16:51:31.635] Transferring table --{ JCR.ICMSTJCRADDTLPROPS}-- to table --{JCR.ICMSTJCRADDTLPROPS }--
     [java] [2018-03-07 16:51:35.563] Transferring table --{ JCR.ICMSTJCRNSPREFIXES}-- to table --{JCR.ICMSTJCRNSPREFIXES }--
     [java] [2018-03-07 16:51:35.681] Transferring table --{ JCR.ICMSTNLSKEYWORDS}-- to table --{JCR.ICMSTNLSKEYWORDS }--
     [java] [2018-03-07 16:51:35.758] error.executing.transfer
     [java] err.dbtransfer.exception.labelclass com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][4.23.42] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
     [java] Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
     [java] com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][4.23.42] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
     [java] Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
     [java]     at com.ibm.db2.jcc.am.ld.a(ld.java:502)
     [java]     at com.ibm.db2.jcc.am.Agent.endBatchedReadChain(Agent.java:434)
     [java]     at com.ibm.db2.jcc.am.bq.a(bq.java:5410)
     [java]     at com.ibm.db2.jcc.am.bq.c(bq.java:4997)
     [java]     at com.ibm.db2.jcc.am.bq.executeBatch(bq.java:3052)
     [java]     at com.ibm.wps.config.db.transfer.DefaultTableHandler.execute(DefaultTableHandler.java:131)
     [java]     at com.ibm.wps.config.db.transfer.TransferEngine.execute(TransferEngine.java:70)
     [java]     at com.ibm.wps.config.db.transfer.CmdLineTransfer.execute(CmdLineTransfer.java:96)
     [java]     at com.ibm.wps.config.db.transfer.CmdLineTransfer.main(CmdLineTransfer.java:43)

BUILD FAILED
/opt/IBM/WebSphere/PortalServer/base/wp.db.impl/config/includes/wp.db.impl_cfg.xml:121: java.util.ConcurrentModificationException

Total time: 8 minutes 17 seconds

stop-wsadmin-listener:
Session is null... creating new for project
[wplc-discard-wsadmin-session] Task parameters:
[wplc-discard-wsadmin-session]   Global attributes:
[wplc-discard-wsadmin-session]     cell=""
[wplc-discard-wsadmin-session]     engineinstalllocation="/opt/IBM/WebSphere/wp_profile/ConfigEngine"
[wplc-discard-wsadmin-session]     enginerootdir="/opt/IBM/WebSphere/ConfigEngine"
[wplc-discard-wsadmin-session]     pathseparator=":"
[wplc-discard-wsadmin-session]     osarch="amd64"
[wplc-discard-wsadmin-session]     node=""
[wplc-discard-wsadmin-session]     server=""

[wplc-discard-wsadmin-session]   Instance attributes (Set 1 of 1):
[wplc-discard-wsadmin-session]     attribute=[ *** NONE_SPECIFIED *** ]
Status = Complete

delete-temp-dirs:

cleanup-work-dir:

cleanup-config:
BUILD FAILED
isIseries currently set to: null

update-registry-sync-property:
     [echo] updated RegistrySynchronized in file wkplc.properties with value: true

print-final-message:
```

**Comment by maryd323** [comment]
Hi ioualha - 

This error has been seen when the DB2_COMPATIBILITY_VECTOR setting is incorrect.  Our readme instructs to set this variable to 0 prior to creating the Portal database.  You can check your value by connecting to the WPSDB and running **db2 get db cfg** ... 

If the output shows that **Varchar2 Compatibility** is **ON**, you will need to drop the WPSDB, run **db2set DB2_COMPATIBILITY_VECTOR=0** in the terminal/command window and re-run the CreateDB2Database and SetupDB2Database.sql scripts; restart db2 and re-run the database transfer.

We are planning to script this process in order to reduce the number of steps involved so there is less possibility of error.

**Comment by ioualha** [comment]
Thanks it works.
